version: '3.9'

services:
  postgres:
    image: postgres:15.2
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: proboardDB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  # socketio:
  #   image: proboard/socketio-image
  #   container_name: proboard-socketio
  #   ports:
  #     - 3500:3500
  #   command: nodemon server/index.ts

  dev:
    image: proboard/nextjs-image
    container_name: proboard-app
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    depends_on:
      - postgres
      # - socketio
    # command: sh -c "npx prisma generate && npx prisma migrate dev --name init && npm run dev"
    command: sh -c "npx prisma generate && npm run dev"

volumes:
  # node_modules:
  postgres-data:
